FROM python:3.12.6

# Create app directory
WORKDIR /app

# Copy only what's needed
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Load env variables from .env
ENV PYTHONUNBUFFERED=1

CMD ["python", "-m", "bot"]
