[phases.setup]
nixPkgs = ["python311", "curl", "coreutils", "cron"]

[phases.install]
cmds = [
  "curl -Lo /usr/local/bin/supercronic https://github.com/aptible/supercronic/releases/latest/download/supercronic-linux-amd64",
  "chmod +x /usr/local/bin/supercronic"
]

[phases.build]
cmds = [
  "mkdir -p /logs"
]

[start]
cmd = "supercronic /cronjob.txt"