[build]
nixpkgs = ["python311", "curl", "coreutils"]

[phases.setup]
cmds = [
  "curl -Lo /usr/local/bin/supercronic https://github.com/aptible/supercronic/releases/latest/download/supercronic-linux-amd64",
  "chmod +x /usr/local/bin/supercronic",
  "mkdir -p /logs"
]

[start]
cmd = "/usr/local/bin/supercronic /cronjob.txt"
